M48
; DRILL file {KiCad (6.0.10)} date Mon Jan 16 00:42:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-16T00:42:21+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X3.6614Y-3.4843
T2
X3.6614Y-3.1289
X3.6614Y-3.2289
T0
M30
